<a href="https://colab.research.google.com/github/rumcrush/cakd3/blob/main/0624%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def add_10(a):
  return a+ 10

add_10(1)

11

In [ ]:
def add_20(a):
  return a + 20

add_20(5)



25

In [ ]:
def add_8(a):
  return a + 80

add_8(8)

88

In [ ]:
def add_9(a):
  return a * 5

add_9(9)

45

In [ ]:
def f1(x):
   a = 3
   b = 5
   y = a * x + b
   return y             # y 값을 반환한다
   
   c = f1(10)             # c = 35 

print(f1(5))

20


In [ ]:
def f1(x):
   a = 3
   b = 5
   y = a * x + b
   print(y) 

d = f1(10)



35


In [ ]:
def cal_3(a,b,c):
  return a * b - c
cal_3(2,3,5)


1

In [ ]:
def cal_4(a,b,c):
  return a * b * c
cal_4(2,5,9)

90

In [ ]:
def cal_4(a,b,f):
  return a * b * f
cal_4(5,8,9)

360

In [ ]:
def cal_5(a,b,c):
  return a + b + c
cal_5(7,8,9)

24

In [ ]:
a = 2
b = 3

s = "구구단 {0} x {1} = {2}".format(a,b, a *b)
print(s)


구구단 2 x 3 = 6


In [ ]:
a = 10 

s = "인사를 {}번 했습니다".format(a)
print(s)

인사를 10번 했습니다


In [ ]:
a = 100000

s = "하루에 숨을 {}번 쉬었습니다".format(a)
print(s)

하루에 숨을 100000번 쉬었습니다


In [ ]:
a = 9000000
s = "손가락이 {}개 있습니다".format(a)

print(s)

손가락이 9000000개 있습니다


In [ ]:
a = '요거트'
b = '바나나'

s = "아침으로 {}와 {}를 먹었습니다".format(a,b)

print(s)

아침으로 요거트와 바나나를 먹었습니다


In [ ]:
a = '에스파'
b = '스테이시'

s = "2020년에 {}와 {}가 데뷔했습니다".format(a,b)

print(s)

2020년에 에스파와 스테이시가 데뷔했습니다


In [ ]:
import datetime
t = datetime.datetime.now()

if t.hour < 12:
  print("현재 시간은 오전 {}시 입니다.".format(t.hour))
else: 
  print("현재 시간은 오후 {}시 입니다".format(t.hour))



현재 시간은 오전 2시 입니다.


In [ ]:
num = input("숫자를 입력하세요 >> ")
num = int(num)

if num % 2 == 0:
  print("짝수입니다")

elif num % 2 == 1:
  print("홀수입니다")




숫자를 입력하세요 >> 50
짝수입니다


In [ ]:
for i in range(1, 20):
  if i % 3 == 0:
    print(i)

3
6
9
12
15
18


In [ ]:
num = input("숫자를 입력하세요 >> ")
num = int(num)

if num % 3 == 0:
  print("3의 배수입니다")

elif num % 5 == 0:
  print("5의 배수입니다")

else:
  print("3과 5의 배수가 아닙니다")



숫자를 입력하세요 >> 19
3과 5의 배수가 아닙니다


In [ ]:
def solution(num):
  if num % 2 == 0:
    return 'Even'
  else:
    return 'Odd'

In [ ]:
a = [1,2,3,4,5]

b = list(map(float, a))
print(b)

[1.0, 2.0, 3.0, 4.0, 5.0]


In [ ]:
a = [7.7, 8.8, 9.9, 5.5, 3.3, 2.2]

b = list(map(int, a))

print(b)

[7, 8, 9, 5, 3, 2]


In [ ]:
a = [7.7, 8.8, 9.9, 5.5, 3.3, 2.2]

b = list(map(str, a))
print(b)

['7.7', '8.8', '9.9', '5.5', '3.3', '2.2']


In [ ]:
a = [1,2,3,4,5]

b = list(map(str, a))
print(b)

['1', '2', '3', '4', '5']


In [ ]:
a = [1,2,3,4,5]

b = list(map(float, b))
print(b)


[1.0, 2.0, 3.0, 4.0, 5.0]


In [ ]:
b = list(map(lambda a : a *a, range(1,6)))
print(b)


[1, 4, 9, 16, 25]


In [ ]:
# 같은 행에 있는 값끼리 묶어주는 zip (리스트로 만들어줌)
print(list(zip([1,2,3], [4,5,6])))
print(list(zip([1,2,3], [4,5,6], [7,8,9])))
print(list(zip(['a','b'], ['b','c'], ['d','e'])))

[(1, 4), (2, 5), (3, 6)]
[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
[('a', 'b', 'd'), ('b', 'c', 'e')]


In [ ]:
# 같은 행에 있는 값끼리 ()로 묶어주는 pair(튜플로 만들어줌)

num = [1, 2, 3]
ltr = ['a', 'b', 'c']

for pair in zip(num, ltr):
  print(pair)

(1, 'a')
(2, 'b')
(3, 'c')


In [ ]:
def avg_number(*args):
  result = 0
  for i in args:
    result += i
  avg = result / len(args)
  return avg
avg_number(1,2,3)

2.0

In [ ]:
strings = ['a', 'bdda', 'cd', 'dd', 'ett']
strings.sort(key=len, reverse=True)
strings

['bdda', 'ett', 'cd', 'dd', 'a']

In [ ]:
strings = ['foo', 'card', 'bar', 'aaaa', 'adsw']
strings.sort(key = lambda x : len(set(x)))
print(strings)


['aaaa', 'foo', 'bar', 'card', 'adsw']


In [ ]:
strings = ['foo', 'card', 'bar', 'aaaa', 'adsw']
strings.sort(key = lambda x : len(set(x)))
print(strings)

['aaaa', 'foo', 'bar', 'card', 'adsw']


In [ ]:
a = ['5', '6', '7', '8', '9']

type(a)

b = list(map(int,a))
print(b)

[5, 6, 7, 8, 9]


In [ ]:
import random
random.random()*10

2.1184339406774355

In [ ]:
import numpy as np
np.random.randint(5, size=5)

array([3, 0, 0, 2, 4])

In [ ]:
np.random.randint(10, size=(5,2))

array([[3, 0],
       [5, 9],
       [6, 3],
       [5, 1],
       [5, 0]])

In [ ]:
np.random.randint(20, size=(3,3))

array([[ 6,  7,  7],
       [16,  2, 14],
       [ 2, 13,  6]])

In [ ]:
np.random.randint(9, size=(2,2))

array([[1, 5],
       [3, 5]])

In [ ]:
def page(a,b):
  if a % b == 0:
    return a // b
  else:
    return a // a +1
print(page(100,3))

2


In [ ]:
import random
han = list ('가나다라마바사아자차카타파하')
han

with open('info.txt', 'w') as file:
  for i in range(1000):
    name = random.choice(han) + random.choice(han)
    height = random.randrange(140, 200)
    weight = random.randrange(40, 100)
    file.write("{},{},{}\n".format(name, height, weight))
  
with open('info.txt', 'r') as file:
  data = file.read()
  print(data)

random.randrange(2,101,2)


카가,158,93
하바,193,45
하바,151,78
파타,148,91
차마,191,46
파다,143,60
카하,192,63
차다,172,95
파자,165,55
마카,186,40
마파,183,42
아바,141,45
파차,182,87
가마,195,79
아사,178,50
아타,176,49
차사,188,58
자카,192,56
카자,180,52
나아,163,93
파바,151,76
바가,160,58
라가,191,84
차자,170,92
사파,182,78
차아,150,63
카타,140,74
바나,174,72
바마,167,58
나바,187,89
자자,162,96
파자,184,81
마하,155,71
나타,184,90
아사,159,94
바다,164,48
차사,194,58
바하,189,50
자하,176,40
하자,190,61
타사,151,91
차아,160,76
아나,162,52
바마,141,88
파바,179,87
사하,142,70
가차,174,58
자가,196,97
나카,151,91
다사,158,82
파타,192,77
나카,189,47
가가,179,91
타하,187,82
하마,198,47
하아,167,72
사마,186,61
바마,160,54
카다,165,61
사마,144,57
자나,182,81
가사,195,88
카마,147,42
사타,188,77
사마,180,83
차하,156,79
다아,196,43
라타,196,52
나파,187,83
파사,140,92
마자,151,92
사파,156,88
라사,158,74
바마,183,88
가타,175,86
다파,180,44
나사,194,60
다라,185,76
가다,151,58
파바,166,60
사카,161,55
카자,156,59
파아,169,86
다바,181,65
가타,161,93
아바,145,52
파자,162,98
가마,144,45
하타,199,98
카다,153,75
나타,181,78
파자,155,93
바하,150,90
나자,150,99
나자,194,44
자차,155,62
카파,159,70
마다,150,40
아하,180,53
사하,192,62


78

In [ ]:
with open("info.txt", 'r') as file:
  data = file.readlines()
  for line in data:
    name, h, w = line.strip().split(',')
    print('이름:{}\n몸무게:{}\n키:\n'.format(name, weight, weight))

이름:카가
몸무게:74
키:

이름:하바
몸무게:74
키:

이름:하바
몸무게:74
키:

이름:파타
몸무게:74
키:

이름:차마
몸무게:74
키:

이름:파다
몸무게:74
키:

이름:카하
몸무게:74
키:

이름:차다
몸무게:74
키:

이름:파자
몸무게:74
키:

이름:마카
몸무게:74
키:

이름:마파
몸무게:74
키:

이름:아바
몸무게:74
키:

이름:파차
몸무게:74
키:

이름:가마
몸무게:74
키:

이름:아사
몸무게:74
키:

이름:아타
몸무게:74
키:

이름:차사
몸무게:74
키:

이름:자카
몸무게:74
키:

이름:카자
몸무게:74
키:

이름:나아
몸무게:74
키:

이름:파바
몸무게:74
키:

이름:바가
몸무게:74
키:

이름:라가
몸무게:74
키:

이름:차자
몸무게:74
키:

이름:사파
몸무게:74
키:

이름:차아
몸무게:74
키:

이름:카타
몸무게:74
키:

이름:바나
몸무게:74
키:

이름:바마
몸무게:74
키:

이름:나바
몸무게:74
키:

이름:자자
몸무게:74
키:

이름:파자
몸무게:74
키:

이름:마하
몸무게:74
키:

이름:나타
몸무게:74
키:

이름:아사
몸무게:74
키:

이름:바다
몸무게:74
키:

이름:차사
몸무게:74
키:

이름:바하
몸무게:74
키:

이름:자하
몸무게:74
키:

이름:하자
몸무게:74
키:

이름:타사
몸무게:74
키:

이름:차아
몸무게:74
키:

이름:아나
몸무게:74
키:

이름:바마
몸무게:74
키:

이름:파바
몸무게:74
키:

이름:사하
몸무게:74
키:

이름:가차
몸무게:74
키:

이름:자가
몸무게:74
키:

이름:나카
몸무게:74
키:

이름:다사
몸무게:74
키:

이름:파타
몸무게:74
키:

이름:나카
몸무게:74
키:

이름:가가
몸무게:74
키:

이름:타하
몸무게:74
키:

이름:하마
몸무게:74
키:

이름:하아
몸무게:74
키:

이름:사마
몸무게:74
키:

이름:바마
몸무게:74
키:

이름:카다
몸무게:74
키

In [ ]:
with open("info.txt", 'r') as file:
  data = file.readlines()
  for line in data:
    name, h, w = line.strip().split(',')
    print('이름 : {} \n 몸무게:\n키:{}'.format(name,w,h))
    
    bmi = int(weight) / ((int(height) / 100) ** 2) 

    if 25 <= bmi:
      result = "과체중"
    elif 18.5 <= bmi:
      result = "정상 체중"
    else:
      result = "저체중"

    print('\n'.join([
          "이름 : {}",
          "몸무게:{}",
          "키 :{}",
          "BMI:{}",
          "결과:{}"
    ]).format(name, weight, height, bmi, result))

    print()

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 차나 
 몸무게:
키:66
이름 : 차나
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 차타 
 몸무게:
키:89
이름 : 차타
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 타마 
 몸무게:
키:69
이름 : 타마
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 라바 
 몸무게:
키:49
이름 : 라바
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 마하 
 몸무게:
키:63
이름 : 마하
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 사사 
 몸무게:
키:75
이름 : 사사
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 다카 
 몸무게:
키:79
이름 : 다카
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 다자 
 몸무게:
키:63
이름 : 다자
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 파차 
 몸무게:
키:67
이름 : 파차
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 마파 
 몸무게:
키:56
이름 : 마파
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 나카 
 몸무게:
키:91
이름 : 나카
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 마바 
 몸무게:
키:62
이름 : 마바
몸무게:74
키 :196
BMI:19.2628071636818
결과:정상 체중

이름 : 마하 
 몸무게:
키:76
이름 : 마하
몸무게:74
키 :196
B

In [ ]:
# 구글 드라이브에서 파일 가져오기 
# 사용자 인증이 안 되서 사용 못 했다 
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
# 컴퓨터에 있는 파일 콜랩으로 가져오기 

from google.colab import files
src = list(files.upload().values())[0]

Saving cal4.py to cal4.py


In [ ]:
# 파일 임포트 후 함수 사용하기 
#cal4(임포트 할 파일 이름).add(사용할 함수 이름) (대입할 값)

NameError: ignored

In [ ]:
# 불필요한 정보 추리는 라이브러리
import warnings

In [ ]:
#산점도 그래프 가져오는 라이브러리 

import seaborn as sns 
tt = sns.load_dataset('titanic')
tt.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [ ]:
tt.age.uniqueb()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
def age_cat(age):
  cat = ''
  if age <=5 : cat = "Baby"
  elif age <=12 : cat = "Child"
  elif age <=18 : cat = "Teenager"
  elif age <=35 : cat = "Young Adult"
  elif age <=60 : cat = "Adult"
  else : cat = 'Elderly'
  return cat

tt['age_cat'] = tt['age'].apply(lambda x : age_cat(x))
tt.head()

survived  pclass     sex   age  ...  embark_town  alive  alone      age_cat
0         0       3    male  22.0  ...  Southampton     no  False  Young Adult
1         1       1  female  38.0  ...    Cherbourg    yes  False        Adult
2         1       3  female  26.0  ...  Southampton    yes   True  Young Adult
3         1       1  female  35.0  ...  Southampton    yes  False  Young Adult
4         0       3    male  35.0  ...  Southampton     no   True  Young Adult

[5 rows x 16 columns]

In [ ]:
# 최대, 최소 
print(max([1,2,3]))
print(max('python'))
print(min([1,2,3]))
print(max('python'))

3
y
1
y


In [ ]:
#파일, 폴더 복사 

import shutil


FileNotFoundError: ignored

In [ ]:
# 1개의 스레드 

import time

def long_task(): # 3초의 시간이 걸리는 함수 
  for i in range(3):
    time.sleep(1) # 1초대기
    print("now loading... %s\n" %i)
print('start')


for i in range(3): #now loading이 3번 반복됨
  long_task()

print("Hello Player")


start
now loading... 0

now loading... 1

now loading... 2

now loading... 0

now loading... 1

now loading... 2

now loading... 0

now loading... 1

now loading... 2

Hello Player


In [215]:
import time
import threading

def long_task(): #5초의 시간이 걸리는 함수
    for i in range(5):
        time.sleep(1) # 1초 대기
        print("%s입금 시 사기전화를 조심하세요!\n"% i)
print('start')

threads = []
for i in range(5):
    t = threading.Thread(target = long_task)
    threads.append(t)
for t in threads:
    t.start()
for t in threads:
    t.join() #join으로 스레드가 종료할 때 까지 기다린다
print('입금되었습니다')


start
0입금 시 사기전화를 조심하세요!

0입금 시 사기전화를 조심하세요!

0입금 시 사기전화를 조심하세요!

0입금 시 사기전화를 조심하세요!

0입금 시 사기전화를 조심하세요!

1입금 시 사기전화를 조심하세요!

1입금 시 사기전화를 조심하세요!

1입금 시 사기전화를 조심하세요!

1입금 시 사기전화를 조심하세요!

1입금 시 사기전화를 조심하세요!

2입금 시 사기전화를 조심하세요!

2입금 시 사기전화를 조심하세요!

2입금 시 사기전화를 조심하세요!

2입금 시 사기전화를 조심하세요!

2입금 시 사기전화를 조심하세요!

3입금 시 사기전화를 조심하세요!

3입금 시 사기전화를 조심하세요!

3입금 시 사기전화를 조심하세요!

3입금 시 사기전화를 조심하세요!

3입금 시 사기전화를 조심하세요!

4입금 시 사기전화를 조심하세요!

4입금 시 사기전화를 조심하세요!

4입금 시 사기전화를 조심하세요!

4입금 시 사기전화를 조심하세요!

4입금 시 사기전화를 조심하세요!

입금되었습니다


In [218]:
month = 1
while month <= 12:
    print(f'2020년 {month}월')
    month += 1



2020년 1월
2020년 2월
2020년 3월
2020년 4월
2020년 5월
2020년 6월
2020년 7월
2020년 8월
2020년 9월
2020년 10월
2020년 11월
2020년 12월


In [222]:
misile = 1
while misile <= 10:
  print(f'돈을 안 주면 미사일 {misile}개를 쏘겠다!')
  misile +=1

돈을 안 주면 미사일 1개를 쏘겠다!
돈을 안 주면 미사일 2개를 쏘겠다!
돈을 안 주면 미사일 3개를 쏘겠다!
돈을 안 주면 미사일 4개를 쏘겠다!
돈을 안 주면 미사일 5개를 쏘겠다!
돈을 안 주면 미사일 6개를 쏘겠다!
돈을 안 주면 미사일 7개를 쏘겠다!
돈을 안 주면 미사일 8개를 쏘겠다!
돈을 안 주면 미사일 9개를 쏘겠다!
돈을 안 주면 미사일 10개를 쏘겠다!


0626 일지 
1) 커뮤니케이션의 중요함을 알게 되었다. 
혼자서 끙끙대며 3시간이고 4시간이고 걸렸던 작업이 잘 하시는 다른 분들께 여쭤보니 너무 금방 끝났다. 

2) 물어본 후 내가 왜 그렇게 했는지 설명하는 것도 공부가 많이 되는 것 같다 

3) 0623-0625 복습을 끝냈다. 내가 약한 부분은 formating이었고 반복문 중에는 while이 약했다. 

4) 포맷팅은 오늘 배운 

month = 1
while month <= 12:
    print(f'2020년 {month}월')    
    month = month + 1

를 사용해 보려고 한다. 

그 밖에 "%s %d" % (a,b) / "{}.format(a,b}" 
이런게 있는데 오지게 안 외워진다 

5) 정규화 할 때 title() << 대문자 처리 

6) 다음주에 클래스 나갈 것 같은데 벌써 걱정된다. 
>> 걱정되는 이유 : 클래스를 직접 짜는게 어렵다. 불러오는건 괜춘 

앞으로 일 하게 되면 내가 직접 테이블을 짤 일보다 전처리 할 일이 더 많지 않을까 생각해본다 
