<a href="https://colab.research.google.com/github/rumcrush/cakd3/blob/main/0707_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# 시리즈 클래스 만들기
#판다스 불러오기(pd)

import pandas as pd

# k : v (딕셔너리 구조) <-딕셔너리 구조를 갖는 딕셔너리를 만들고 dict_data에 저장 

dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data)
print(sr)

print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [7]:
import pandas as pd 

a_da = {'d': 5, 'e' : 'apple', 'c':10}
sr = pd.Series(a_da)
print(sr)


d        5
e    apple
c       10
dtype: object


In [8]:
import pandas as pd 

b_da = {'k' : 'li', 'l' : 80, 'm':'boo'}
sr = pd.Series(b_da)
print(sr)  

k     li
l     80
m    boo
dtype: object


In [9]:
#리스트를 시리즈로 변환 
import pandas as pd 

list_data = ['2019-07-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data,index=list('abcde'))
sr

a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [10]:
import pandas as pd 

list_test = ['2020-09-12', 77, 'SDA', 900, False]
sr = pd.Series(list_test, index=list('12345'))
sr


1    2020-09-12
2            77
3           SDA
4           900
5         False
dtype: object

In [11]:
#인덱스 및 값 가져오기
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['1', '2', '3', '4', '5'], dtype='object')
['2020-09-12' 77 'SDA' 900 False]


In [ ]:
idx = sr.index #인덱스가져오기
val = sr.values  #값 가져오기

print(idx)
print(val)

Index(['1', '2', '3', '4', '5'], dtype='object')
['2020-09-12' 77 'SDA' 900 False]


In [ ]:
#튜플을 시리즈를 변환하고 자료를 리스트로 만들기
tup_data = ('onefive','2019-07-02', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)


In [ ]:
tup_data_01 = ('吉田爽葉香', '2004-6-14', '女性', True)
sr = pd.Series(tup_data_01, index=['名前','生年月日','性別','onefive'])

print(sr)

名前             吉田爽葉香
生年月日       2004-6-14
性別                女性
onefive         True
dtype: object


In [ ]:
# 배열 
import numpy as np 
s1 = np.arange(11,16)
print(type(s1),s1)

#배열에 인덱스 값 주기 활용 
s2 = pd.Series(s1,index=list('abcde'))
print(type(s2),s2)

<class 'numpy.ndarray'> [11 12 13 14 15]
<class 'pandas.core.series.Series'> a    11
b    12
c    13
d    14
e    15
dtype: int64


In [ ]:
import numpy as np

s3 = np.arange(20,25)
print(type(s3),s3)

print()
s4 = pd.Series(s2,index=list('12345'))
print(type(s4), s4)


<class 'numpy.ndarray'> [20 21 22 23 24]

<class 'pandas.core.series.Series'> 1    20
2    21
3    22
4    23
5    24
dtype: int64


In [ ]:
import numpy as np
s3 = np.arange(1000,5000, 1000)
print(s3)

sr = pd.Series(s3, index=['Califonia','Ohio','Oregon','Texas'])
print(sr)


[1000 2000 3000 4000]
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
dtype: int64


In [ ]:
import numpy as np

s5 = np.arange(300,1000,300)
print(s5)

sr = pd.Series(s5, index=['tokyo', 'seoul','london'])
print(sr)


[300 600 900]
tokyo     300
seoul     600
london    900
dtype: int64


In [ ]:
data = np.arange(1000,5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']
obj = pd.Series(data, index=state)

# 데이터에 이름 넣기 
obj.name = 'population'

#인덱스에 이름 넣기
obj.index.name = 'state'

#시리즈의 객체인 obj
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64

In [ ]:
test = np.arange(200,1000,200)
country = ['japan', 'korea', 'usa', 'uk']
obj = pd.Series(test, index=country)

obj.name = 'namae'

obj.index.name = 'country'

obj


country
japan    200
korea    400
usa      600
uk       800
Name: namae, dtype: int64

In [ ]:
#값을 교체하기 
obj.japan = np.nan
obj

obj.japan = 900
obj

obj.korea = 1000
obj

obj.uk = np.nan
obj


country
japan     900.0
korea    1000.0
usa       600.0
uk          NaN
Name: namae, dtype: float64

In [ ]:
#null값 개수 찾기 
obj.isnull().sum()


1

In [19]:
#배열을 데이터 프레임으로 변환 
# np.random.randint 숫자를 랜덤으로 불러옴 
np.random.seed(0) #값을 고정한다 
data = np.random.randint(100,120, size=(3,3)) #3행 3열의 데이터를 뽑겠다 
print(data, type(data))

df = pd.DataFrame(data,index=['d1','d2','d3'], #행 인덱스 (보통 인덱스는 행을 이야기함)
                 columns = ['pd','sales','inv']) #컬럼지정

df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [20]:
np.random.seed(0)
data = np.random.randint(100,500, size=(5,5))
print(data, type(data))

df = pd.DataFrame(data, index=[900,1000,500,300,2000],
                  columns = ['apple','banana','melon','cherry','orange'])

df


[[272 147 217 292 423]
 [351 295 459 109 311]
 [377 342 392 187 170]
 [188 496 414 293 139]
 [187 274 188 437 265]] <class 'numpy.ndarray'>


apple  banana  melon  cherry  orange
900     272     147    217     292     423
1000    351     295    459     109     311
500     377     342    392     187     170
300     188     496    414     293     139
2000    187     274    188     437     265

In [21]:
#pandas indexing : iloc와 loc를 쓴다 
#iloc : 정수 인덱스, 숫자로 인덱스를 찾을 떄 쓴다
#loc : 이름 인덱스, 인덱스의 이름으로 찾을 떄 쓴다  

print(df.iloc[3],'\n')
df.loc[900,'melon']


apple     188
banana    496
melon     414
cherry    293
orange    139
Name: 300, dtype: int64 



217

In [22]:
print(df.iloc[4],'\n')
df.loc[500, 'orange']

print(df.iloc[3],'\n')
df.loc[2000,'banana']

print(df.iloc[1],'\n')
df.loc[300, 'cherry']

apple     187
banana    274
melon     188
cherry    437
orange    265
Name: 2000, dtype: int64 

apple     188
banana    496
melon     414
cherry    293
orange    139
Name: 300, dtype: int64 

apple     351
banana    295
melon     459
cherry    109
orange    311
Name: 1000, dtype: int64 



293

In [23]:
print(df.iloc[2,1])
print(df.iloc[3,4])
print(df.loc[2000,'melon'])

342
139
188


In [24]:
df.loc[600] = 0 
df

apple  banana  melon  cherry  orange
900     272     147    217     292     423
1000    351     295    459     109     311
500     377     342    392     187     170
300     188     496    414     293     139
2000    187     274    188     437     265
600       0       0      0       0       0

In [25]:
print(df.loc['d3'])

df.loc['d3']=0
df

KeyError: ignored

In [26]:
id = np.arange(1,501)
i1 = pd.Series(id)

i1

gender = np.arange(0,2)
i2 = pd.Series(gender)
i2


age = np.arange(1,101)
i3 = pd.Series(age)
i3

region = np.arange(1,100)
i4 = pd.Series(region)
i4


0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

In [27]:
id = np.arange(1,51)
i1 = pd.Series(id)

gender = np.random.randint(2, size=50)
g1 = pd.Series(gender)

age = np.random.randint(1,101, size=50)
a1 = pd.Series(age)

region = np.random.randint(1,100, size = 50)
r1 = pd.Series(region)

df_01 = pd.concat([i1,g1,a1,r1], axis=1)

df_01.rename(columns={0:'id', 1:'gender', 2:'age', 3:'region'}, inplace=True)
df_01


id  gender  age  region
0    1       1    5      49
1    2       1   43      94
2    3       0   59       4
3    4       1   32      99
4    5       0    2      43
5    6       1   66      78
6    7       0   42      22
7    8       1   58      74
8    9       1   36       1
9   10       0   12      11
10  11       1   47      44
11  12       1   83      59
12  13       0   92      24
13  14       0    1      60
14  15       1   15       3
15  16       0  100      99
16  17       1   54      63
17  18       1   13      36
18  19       1   43      95
19  20       1   85      68
20  21       1   76      83
21  22       0   69      47
22  23       1    7      21
23  24       0   69      82
24  25       1   48      51
25  26       1    4      28
26  27       1   77      15
27  28       1   53      42
28  29       0   79      59
29  30       1   16      66
30  31       0   21      37
31  32       0  100      11
32  33       1   59      87
33  34       1   24      44
34  35       0   80      12
35  36       1   14       3
36  37       0   86      52
37  38       1   49      81
38  39       0   50      33
39  40       0   70      55
40  41       0   42       1
41  42       0   36      39
42  43       0   65      20
43  44       1   96      47
44  45       1   70      43
45  46       0   95      57
46  47       0    1      61
47  48       0   51      78
48  49       1   37      31
49  50       1   35      25

In [28]:
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size=1000) #size = 1000 개수를 1000 개 뽑아줘라
g1 = pd.Series(gender)
age = np.random.randint(1,101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11, size=1000)
r1 = pd.Series(region)


df_01 = pd.concat([i1,g1,a1,r1],axis=1) 
#concat : 합치는 함수 #concat에 리스트 형태로 넣어라 #axis =1 (열방향으로 합쳐라, axis=0은 행방향으로 합쳐라 )
#rename : 이름을 바꿔라 (딕셔너리로 처리 해야함)
#inplace=True > 변경한 내용을 원본에 적용해라 
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'}, inplace=True)
df

apple  banana  melon  cherry  orange
900     272     147    217     292     423
1000    351     295    459     109     311
500     377     342    392     187     170
300     188     496    414     293     139
2000    187     274    188     437     265
600       0       0      0       0       0

In [29]:
df_02 = df_01[:] #df_01을 df_02라는 이름으로 복사하기
df_02

df_03 = df_02.copy() #df_02를 df_03라는 이름으로 복사하기 
df_03

df_03.head(3) #df_03 3개만 가져오기
df_02.head(1) #df_02 1개만 가져오기 

0  1  2  3
0  1  1  2  6

In [30]:
# 데이터 프레임 복사해서 쓰기
df1 = df[:]
df1

df1 = df.copy() #자주 씀 
df

#앞의 내용 5개만 보여달라 
df1.head()

#앞의 내용 3개만 보여달라 

df1.head(3)

#뒤의 내용 3개만 보여달라
# df1.tail(3)

apple  banana  melon  cherry  orange
900     272     147    217     292     423
1000    351     295    459     109     311
500     377     342    392     187     170

In [31]:
df_01.iloc[:2]
df_01.head()

0  1   2  3
0  1  1   2  6
1  2  0  30  5
2  3  1   6  4
3  4  0  81  6
4  5  0  41  8

In [32]:
df1.iloc[:2] = np.nan#0-1행으로 범위 지정
df1.head()

apple  banana  melon  cherry  orange
900     NaN     NaN    NaN     NaN     NaN
1000    NaN     NaN    NaN     NaN     NaN
500   377.0   342.0  392.0   187.0   170.0
300   188.0   496.0  414.0   293.0   139.0
2000  187.0   274.0  188.0   437.0   265.0

In [33]:
b = np.random.randint(20,31, size = (2,5))
print(b)


[[24 30 22 25 24]
 [30 22 20 29 21]]


In [34]:
import numpy as np


b = np.random.randint(1,100, size=(3,5))
print(b)

[[70 94 80 90 25]
 [61 65 62 78 13]
 [71 50  4 33 50]]


In [35]:
a = np.random.randint(1,5,size=(10,5)) #10행 5열짜리 2차원 리스트를 만들어라 
print(a)

[[4 2 4 2 1]
 [4 4 3 3 1]
 [2 3 1 1 2]
 [2 4 4 1 1]
 [1 4 3 2 1]
 [4 4 2 3 1]
 [2 4 3 1 4]
 [4 2 4 1 4]
 [2 2 3 3 4]
 [4 4 3 3 4]]


In [36]:
# 2차원리스트를 데이터프레임으로 변환 
list1 = a.tolist()
print(list1,type(list1))

#위에서 만든 리스트를 데이터 프레임으로 변환 
df1 = pd.DataFrame(list1,columns=['c1','c2','c3','c4','c5'])
print(df1)

[[4, 2, 4, 2, 1], [4, 4, 3, 3, 1], [2, 3, 1, 1, 2], [2, 4, 4, 1, 1], [1, 4, 3, 2, 1], [4, 4, 2, 3, 1], [2, 4, 3, 1, 4], [4, 2, 4, 1, 4], [2, 2, 3, 3, 4], [4, 4, 3, 3, 4]] <class 'list'>
   c1  c2  c3  c4  c5
0   4   2   4   2   1
1   4   4   3   3   1
2   2   3   1   1   2
3   2   4   4   1   1
4   1   4   3   2   1
5   4   4   2   3   1
6   2   4   3   1   4
7   4   2   4   1   4
8   2   2   3   3   4
9   4   4   3   3   4


In [41]:
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))

df = pd.DataFrame(data,index=['d1,','d2','d3'],
                  columns=['pd','sales','inv'])

df

pd  sales  inv
d1,  112    115  100
d2   103    103  107
d3   109    119  118

In [44]:
np.random.seed(0)
data = np.random.randint(1,3, size=(3,3
                                    ))
test = pd.DataFrame(data,index=['a1','a2','a3'],
                  columns=['apple','banana','melon'])

test

apple  banana  melon
a1      1       2      2
a2      1       2      2
a3      2       2      2

In [53]:
test.loc['a1','apple']
test.iloc[0,0]

test.iloc[2,2]
test.loc['a3','melon']

test.iloc[0,1]
test.loc['a1','banana']

2

In [84]:
id = np.arange(1,1001)
i1 = pd.Series(id)
i1


gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)

age = np.random.randint(1,101, size=1000)
a1 = pd.Series(age)
a1

region = np.random.randint(1,100,size=1000)
r1 = pd.Series(region)
r1

#직업종류
job = np.random.randint(1,100, size=1000)
j1 = pd.Series(job)

#구매 여부
buy = np.random.randint(2, size=1000)
b1 = pd.Series(buy)


#재구매
rebuy = np.random.randint(1,100, size=1000)
rb1 = pd.Series((rebuy))

#결제수단
money = np.random.randint(1,10, size=1000)
m1 = pd.Series(money)

#vip여부 
vip = np.random.randint(2, size=100)
v1 = pd.Series(vip)



df = pd.concat([i1, g1, a1, r1,j1, b1, rb1,m1, v1], axis=1)
df.rename(columns={0:'id', 1:'gender', 2:'age', 3:'region', 4:'job', 5:'buy', 6:'rebuy', 7:'money', 8:'vip'},inplace=True)
df


id  gender  age  region  job  buy  rebuy  money  vip
0       1       1   79      43   46    1     44      2  0.0
1       2       1   91      38   55    0     25      9  1.0
2       3       0   86      48   31    0     89      6  1.0
3       4       0   14      13   13    0     39      6  1.0
4       5       1   75      29   49    1      1      7  1.0
..    ...     ...  ...     ...  ...  ...    ...    ...  ...
995   996       1   21      69   40    1     57      5  NaN
996   997       1   87      80   69    0     55      9  NaN
997   998       1   21      44   50    1     31      8  NaN
998   999       1    2      93   50    0     21      8  NaN
999  1000       1   83      81   10    1     46      4  NaN

[1000 rows x 9 columns]

In [87]:
list1 = a.tolist()
print(list1,type(list))

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1.head(4))

[[4, 2, 4, 2, 1], [4, 4, 3, 3, 1], [2, 3, 1, 1, 2], [2, 4, 4, 1, 1], [1, 4, 3, 2, 1], [4, 4, 2, 3, 1], [2, 4, 3, 1, 4], [4, 2, 4, 1, 4], [2, 2, 3, 3, 4], [4, 4, 3, 3, 4]] <class 'type'>
   c1  c2  c3  c4  c5
0   4   2   4   2   1
1   4   4   3   3   1
2   2   3   1   1   2
3   2   4   4   1   1


In [91]:
c = np.random.randint(15,20, size=(20,5))
c

array([[18, 18, 15, 18, 16],
       [16, 18, 18, 16, 15],
       [17, 18, 16, 17, 15],
       [19, 17, 17, 15, 17],
       [16, 15, 16, 16, 18],
       [18, 18, 17, 16, 16],
       [15, 17, 18, 16, 16],
       [19, 16, 18, 19, 18],
       [18, 17, 15, 19, 19],
       [19, 17, 15, 18, 19],
       [15, 16, 15, 17, 19],
       [19, 19, 17, 15, 16],
       [17, 18, 18, 17, 19],
       [19, 19, 19, 16, 18],
       [15, 19, 17, 19, 19],
       [15, 18, 15, 18, 17],
       [16, 18, 15, 15, 16],
       [18, 18, 18, 15, 16],
       [15, 19, 18, 15, 15],
       [18, 18, 19, 19, 16]])

In [93]:
list2 = c.tolist()
print(list2,type(list2))

df1 = pd.DataFrame(list2, columns=['c1','c2','c3','c4','c5'])
print(df1.head(5))

[[18, 18, 15, 18, 16], [16, 18, 18, 16, 15], [17, 18, 16, 17, 15], [19, 17, 17, 15, 17], [16, 15, 16, 16, 18], [18, 18, 17, 16, 16], [15, 17, 18, 16, 16], [19, 16, 18, 19, 18], [18, 17, 15, 19, 19], [19, 17, 15, 18, 19], [15, 16, 15, 17, 19], [19, 19, 17, 15, 16], [17, 18, 18, 17, 19], [19, 19, 19, 16, 18], [15, 19, 17, 19, 19], [15, 18, 15, 18, 17], [16, 18, 15, 15, 16], [18, 18, 18, 15, 16], [15, 19, 18, 15, 15], [18, 18, 19, 19, 16]] <class 'list'>
   c1  c2  c3  c4  c5
0  18  18  15  18  16
1  16  18  18  16  15
2  17  18  16  17  15
3  19  17  17  15  17
4  16  15  16  16  18


In [100]:
d = np.random.randint(5,10, size=(2,5))
d

list3 = d.tolist()
print(list3)

df2 = pd.DataFrame(list3, columns=['c1','c2','c3','c4','c5'])
print(df2. head(1))

[[7, 9, 7, 8, 5], [8, 7, 8, 7, 6]]
   c1  c2  c3  c4  c5
0   7   9   7   8   5


In [106]:
ar = df2.values #배열로 만들기
li = ar.tolist() #리스트로 만들기
dict = df2.to_dict('list') #딕셔너리로 만들기
print(dict)

{'c1': [7, 8], 'c2': [9, 7], 'c3': [7, 8], 'c4': [8, 7], 'c5': [5, 6]}


In [107]:
file_data = pd.DataFrame({
    'col1' : [1,2,3,4,5,6],
    'col2' : ['A','B','C','D','E','F']
})

print(file_data)

   col1 col2
0     1    A
1     2    B
2     3    C
3     4    D
4     5    E
5     6    F


In [114]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})

df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['F','E','G'])

})

print(df_1)

   col1 col2
0     1    A
1     2    B
2     3    C


In [117]:
df_3 = pd.concat([df_1, df_2], axis=1)
df_3

df_4 = pd.concat([df_1, df_2])
df_4

col1 col2
0     1    A
1     2    B
2     3    C
0     4    F
1     5    E
2     6    G

In [130]:
print(df_4['col2'])
print(df_3['col1'])
print(df_4['col1'])

df_5 = df_4.copy()
df_5

df_6 = df_4.drop('col1',axis=1) #열방향 
df_6

0    A
1    B
2    C
0    F
1    E
2    G
Name: col2, dtype: object
   col1  col1
0     1     4
1     2     5
2     3     6
0    1
1    2
2    3
0    4
1    5
2    6
Name: col1, dtype: int64


col2
0    A
1    B
2    C
0    F
1    E
2    G

In [132]:
#첫 행만 출력
df_3.query('index==0')

col1 col2  col1 col2
0     1    A     4    F

In [140]:
df_3

df_3.query('c3 ==3')
df_3.query('c3==2 & c4 ==2')
df_3.query('c3==2 | c4 ==2')
df_3.query('c3==3')[['c3', 'c4']]


UndefinedVariableError: ignored

In [145]:
df_e = df_3[:3]
df_e

col1 col2  col1 col2
0     1    A     4    F
1     2    B     5    E
2     3    C     6    G

In [146]:
import warnings

warnings.filterwarnings('ignore')
df_e.rename(columns = {'a1' : 'first_single', 'a2' : 'second_single', 'a3' : 'third_single', 'a4' : 'forth_single', 'a5' : 'fith_single'},
            index = {0 : 'pinky promise', 1 : 'まだ見ぬ世界', 2:'雫', 3 : 'B.B.B', 4:'Lalala Lucky'}, inplace=True)

df_e

col1 col2  col1 col2
pinky promise     1    A     4    F
まだ見ぬ世界            2    B     5    E
雫                 3    C     6    G

In [147]:
df_e.iloc[0,3]

'F'

학원을 다니고 처음으로 복습까지 포함해서 12시에 끝난 날이다. 

판다스를 처음 배웠을 때는 비교적 쉬웠다. 
기존에 예습했던 내용이 나와서 수월했다. 그런데 수업 중간에 기기 문제가 생겨서 수업을 30분 동안 못 들었고 많은 내용들을 놓치고 수업을 못 따라가서 당황했다. 

다행히 학우분들께 물어봐서 오늘 진도를 따라 잡을 수 있었다. 

어제 같았으면 혼자서 끙끙 앓으면서 1시까지 잡고 있던 과제도 
모르는 걸 물어보면서 하니까 8시 전에 과제를 끝낼 수 있어서 너무 좋았다. 

더 부족한 내용이 있어서 집에 와서도 남은 복습을 계속 했다. 
np.array, random.randint(n,n1 size=n2)를 써보면서 
고객 구매 관리, 고객 등급 관리가 생각나서 시리즈로도 만들어봤는데 좀더 직관적으로 이해하기 좋았다.

부족한 부분은 혼자 구글에서 찾아보면 답이 나올 거라고 생각했다. 
하지만 같이 공부하는 나보다 잘 하는 분들께 물어보는게 훨씬 빠르고 이해도 잘 된다는 것을 알 수 잇었다. 
반성하게 된다. 커뮤니케이션이 이렇게나 중요한데. 
