In [ ]:
# 시리즈, 데이터 프레임은 클래스이다


In [12]:
# 시리즈 클래스 만들기
#판다스 불러오기(pd)

import pandas as pd

# k : v (딕셔너리 구조) <-딕셔너리 구조를 갖는 딕셔너리를 만들고 dict_data에 저장 

dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data)
print(sr)

print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [13]:
#리스트를 시리즈로 변환 
import pandas as pd 

list_data = ['2019-07-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data,index=list('abcde'))
sr

a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [16]:
#인덱스 및 값 가져오기
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['이름', '생년월일', '성별', '학생여부'], dtype='object')
['onefive' '2019-07-02' '여' True]


In [15]:
#튜플을 시리즈를 변환하고 자료를 리스트로 만들기
tup_data = ('onefive','2019-07-02', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)


이름         onefive
생년월일    2019-07-02
성별               여
학생여부          True
dtype: object


In [17]:
#인덱싱 

print(sr[0])

#인덱스의 이름으로도 찾을 수 있따 
print(sr['이름'])

#리스트 형태로 인덱싱 (찾는 내용이 1개 이상이기 떄문에 리스트의 리스트로 만들어야한다)
print(sr[[1,2]])

onefive
onefive
생년월일    2019-07-02
성별               여
dtype: object


In [17]:
# 배열 
import numpy as np 
s1 = np.arange(11,16)
print(type(s1),s1)

#배열에 인덱스 값 주기 활용 
s2 = pd.Series(s1,index=list('abcde'))
print(type(s2),s2)

<class 'numpy.ndarray'> [11 12 13 14 15]
<class 'pandas.core.series.Series'> a    11
b    12
c    13
d    14
e    15
dtype: int64


In [18]:
import numpy as np
s3 = np.arange(1000,5000, 1000)
print(s3)

sr = pd.Series(s3, index=['Califonia','Ohio','Oregon','Texas'])
print(sr)


[1000 2000 3000 4000]
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
dtype: int64


In [20]:
data = np.arange(1000,5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']
obj = pd.Series(data, index=state)

# 데이터에 이름 넣기 
obj.name = 'population'

#인덱스에 이름 넣기
obj.index.name = 'state'

#시리즈의 객체인 obj
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64

In [21]:
#값을 교체하기 
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [22]:
#null값 개수 찾기 
obj.isnull().sum()

1

In [23]:
#배열을 데이터 프레임으로 변환 
# np.random.randint 숫자를 랜덤으로 불러옴 
np.random.seed(0) #값을 고정한다 
data = np.random.randint(100,120, size=(3,3)) #3행 3열의 데이터를 뽑겠다 
print(data, type(data))

df = pd.DataFrame(data,index=['d1','d2','d3'], #행 인덱스 (보통 인덱스는 행을 이야기함)
                 columns = ['pd','sales','inv']) #컬럼지정

df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [73]:
#pandas indexing : iloc와 loc를 쓴다 
#iloc : 정수 인덱스, 숫자로 인덱스를 찾을 떄 쓴다
#loc : 이름 인덱스, 인덱스의 이름으로 찾을 떄 쓴다  

print(df.iloc[1], '\n')
print(df.loc['d2'])


pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [25]:
print(df.iloc[1][1])
print(df.iloc[1,1])
print(df.loc['d2','sales'])

103
103
103


In [26]:
print(df.loc['d3'])

df.loc['d3']=0
df

pd       109
sales    119
inv      118
Name: d3, dtype: int64


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [27]:
#새로운 행 추가 
df.loc['d4'] = 0 
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [ ]:
#df.loc[:,"inv"] 이렇게 하면 모든 열에서 inv 행을 뽑을수있습니다

In [28]:
# 데이터 프레임 만들기
id = np.arange(1,1001)
i1 = pd.Series(id)

i1

gender = np.arange(0,2)
i2 = pd.Series(gender)

i2

age = np.arange(1,101)
i3 = pd.Series(age)

i3

region = np.arange(1,100)
i4 = pd.Series(region)

i4

0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

In [29]:
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size=1000) #size = 1000 개수를 1000 개 뽑아줘라
g1 = pd.Series(gender)
age = np.random.randint(1,101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11, size=1000)
r1 = pd.Series(region)


df_01 = pd.concat([i1,g1,a1,r1],axis=1) 
#concat : 합치는 함수 #concat에 리스트 형태로 넣어라 #axis =1 (열방향으로 합쳐라, axis=0은 행방향으로 합쳐라 )
#rename : 이름을 바꿔라 (딕셔너리로 처리 해야함)
#inplace=True > 변경한 내용을 원본에 적용해라 
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'}, inplace=True)
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [ ]:
# 과제 
# 위의 데이터에 적합한 컬럼 5개를 추가하여 출력하세요 

In [30]:
# 데이터 프레임 복사해서 쓰기
df1 = df[:]
df1

df1 = df.copy() #자주 씀 
df

#앞의 내용 5개만 보여달라 
df1.head()

#앞의 내용 3개만 보여달라 

df1.head(3)

#뒤의 내용 3개만 보여달라
# df1.tail(3)

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [31]:
df1.iloc[:2] = np.nan#0-1행으로 범위 지정
df1.head()

pd  sales  inv
d1  NaN    NaN  NaN
d2  NaN    NaN  NaN
d3  0.0    0.0  0.0
d4  0.0    0.0  0.0

In [32]:
a = np.random.randint(1,5,size=(10,5)) #10행 5열짜리 2차원 리스트를 만들어라 
print(a)

[[2 1 4 1 3]
 [3 4 1 3 3]
 [2 1 1 2 3]
 [2 2 2 3 4]
 [4 4 2 4 1]
 [4 3 2 2 4]
 [2 2 2 2 1]
 [3 1 4 4 2]
 [2 4 2 1 2]
 [1 3 1 4 4]]


In [118]:
# 2차원리스트를 데이터프레임으로 변환 
list1 = a.tolist()
print(list1,type(list1))

#위에서 만든 리스트를 데이터 프레임으로 변환 
df1 = pd.DataFrame(list1,columns=['c1','c2','c3','c4','c5'])
print(df1)


[[3, 3, 3, 3, 1], [3, 3, 1, 3, 3], [4, 4, 2, 1, 1], [1, 4, 2, 2, 3], [4, 3, 1, 4, 3], [2, 2, 1, 1, 4], [2, 4, 2, 3, 3], [4, 4, 2, 4, 1], [2, 2, 2, 2, 1], [3, 1, 3, 4, 3]] <class 'list'>
   c1  c2  c3  c4  c5
0   3   3   3   3   1
1   3   3   1   3   3
2   4   4   2   1   1
3   1   4   2   2   3
4   4   3   1   4   3
5   2   2   1   1   4
6   2   4   2   3   3
7   4   4   2   4   1
8   2   2   2   2   1
9   3   1   3   4   3


In [33]:
#데이터 프레임을 numpy(배열),list,dictionary로 변환하기 

#numpy(배열)
ar = df1.values
print(ar, type(ar))
print()

#리스트
li = ar.tolist()
print(li, type(li))
print()

#딕셔너리
dict = df1.to_dict('list')
print(dict,type(dict))

[[nan nan nan]
 [nan nan nan]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] <class 'numpy.ndarray'>

[[nan, nan, nan], [nan, nan, nan], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]] <class 'list'>

{'pd': [nan, nan, 0.0, 0.0], 'sales': [nan, nan, 0.0, 0.0], 'inv': [nan, nan, 0.0, 0.0]} <class 'dict'>


In [34]:
#file 생성 
#값은 리스트로 넣기
file_data = pd.DataFrame({
    'col1' : [1,2,3,4,5,6],
    'col2' : ['A','A','B','B','C','C']
})

print(file_data)





   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [35]:
#file 저장 
file_data.to_csv('dataset/file_data.csv',index=None)

In [139]:
#file 불러오기 
file_data = pd.read_csv('dataset/file_data.csv')
file_data
print(file_data,type(file_data))

#판다스는 라이브러리, 데이터프레임이 클래스 이름


   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C <class 'pandas.core.frame.DataFrame'>


In [56]:
df_1 = pd.DataFrame({
    'col1' : np.array([1,2,3]),
    'col2' : np.array(['A','B','C'])
})

df_2 = pd.DataFrame({
    'col1' : np.array([4,5,6]),
    'col2' : np.array(['D','E','F'])
})

In [57]:
df_3 = pd.concat([df_1,df_2],axis=1)
df_4 = pd.concat([df_1,df_2]) #행방향이 기본값

print(df_3)
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F
   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [58]:
df_4

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [58]:
# Q. df_1과 df_2를 행방향과 열방향으로 병합하여 출력하세요.
df_3 =pd.concat([df_1,df_2],axis=1)
df_4 =pd.concat([df_1,df_2])
print(df_3)
print()
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [60]:
# Q. df_1과 df_2를 행방향과 열방향으로 병합하여 출력하세요.
df_3 =pd.concat([df_1,df_2],axis=1)
df_4 =pd.concat([df_1,df_2])
print(df_3)
print()
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [61]:
df_4

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [62]:
#데이터 추출 
print(df_4.col2) #컬럼 하나만 뽑아서 시리즈 형태로 나옴 
print(df_4['col2'])

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object
0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object


In [63]:
# pd.DataFrame(df_4['col2'])
df_4[['col1']]

col1
0     1
1     2
2     3
0     4
1     5
2     6

In [64]:
# 열 삭제
df = df1.copy()
df_a = df.drop('c1',axis=1)
df_a

c2  c3  c4  c5
0   3   2   2   1
1   4   4   4   3
2   3   2   4   1
3   4   1   1   1
4   1   4   4   1
5   4   2   4   4
6   1   1   2   2
7   2   1   4   4
8   3   4   1   1
9   1   3   2   1

In [67]:
# 첫행만 출력
df.query('index==0')

c1  c2  c3  c4  c5
0   2   3   2   2   1

In [102]:
#c3에 
df_a.query('c3==3')

c2  c3  c4  c5
9   1   3   2   1

In [103]:
df_a.query('c3==2 & c4==2')

c2  c3  c4  c5
0   3   2   2   1

In [104]:
df_a.query('c3==2 | c4==2')

c2  c3  c4  c5
0   3   2   2   1
2   3   2   4   1
5   4   2   4   4
6   1   1   2   2
9   1   3   2   1

In [105]:
df_a.query('c3==3')[['c3','c4']]

c3  c4
9   3   2

In [71]:
df_e = df[:3] #3행 이전까지 슬라이싱 해라 
df_e

c1  c2  c3  c4  c5
0   2   3   2   2   1
1   4   4   4   4   3
2   1   3   2   4   1

In [72]:
import warnings
warnings.filterwarnings('ignore')
df_e.rename(columns={'c1':'국어','c2':'영어','c3':'수학','c4':'과학','c5':'음악'},
            index={0:'권준기',1:'우동주',2:'임희진'},inplace=True)
df_e

국어  영어  수학  과학  음악
권준기   2   3   2   2   1
우동주   4   4   4   4   3
임희진   1   3   2   4   1

In [16]:
import numpy as np 
import pandas as pd

a = np.random.randint(1,5,size=(10,5))

list1 = a.tolist()
print(list1,type(list1))

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1)

[[2, 3, 2, 2, 1], [4, 4, 4, 4, 3], [1, 3, 2, 4, 1], [3, 4, 1, 1, 1], [3, 1, 4, 4, 1], [4, 4, 2, 4, 4], [1, 1, 1, 2, 2], [1, 2, 1, 4, 4], [2, 3, 4, 1, 1], [2, 1, 3, 2, 1]] <class 'list'>
   c1  c2  c3  c4  c5
0   2   3   2   2   1
1   4   4   4   4   3
2   1   3   2   4   1
3   3   4   1   1   1
4   3   1   4   4   1
5   4   4   2   4   4
6   1   1   1   2   2
7   1   2   1   4   4
8   2   3   4   1   1
9   2   1   3   2   1


In [77]:
#열 삭제
df = df1.copy()
df_a = df.drop('c1',axis=1)
df_a

c2  c3  c4  c5
0   3   2   2   1
1   4   4   4   3
2   3   2   4   1
3   4   1   1   1
4   1   4   4   1
5   4   2   4   4
6   1   1   2   2
7   2   1   4   4
8   3   4   1   1
9   1   3   2   1

In [107]:
#쿼리지정
df_a.query('index==0')

c2  c3  c4  c5
0   3   2   2   1

In [84]:
# 첫행만 출력
df.query('index==0')

c1  c2  c3  c4  c5
0   2   3   2   2   1

In [19]:
df.query('c3==3') #컬럼 c3에 있는 것만 가져오기

c1  c2  c3  c4  c5
9   2   1   3   2   1

In [79]:
df.query('c3==2 & c4==2') #and조건 

c1  c2  c3  c4  c5
0   2   3   2   2   1

In [80]:
df.query('c3==2 | c4==2') #or조건

c1  c2  c3  c4  c5
0   2   3   2   2   1
2   1   3   2   4   1
5   4   4   2   4   4
6   1   1   1   2   2
9   2   1   3   2   1

In [81]:
df.query('c3==3')[['c3','c4']]

c3  c4
9   3   2

In [62]:
#도움말이 필요할 때 
help(df.query)

Help on method query in module pandas.core.frame:

query(expr, inplace=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that are not valid Python variable names
        by surrounding them in backticks. Thus, column names containing spaces
        or punctuations (besides underscores) or starting with digits must be
        surrounded by backticks. (For example, a column named "Area (cm^2) would
        be referenced as `Area (cm^2)`). Column names which are Python keywords
        (like "list", "for", "import", etc) cannot be used.
    
        For example, if one of your columns is called ``a a`` and you want
        to sum it with ``b``, your quer

In [89]:
df_3 = df[:3]
df_e

국어  영어  수학  과학  음악
권준기   2   3   2   2   1
우동주   4   4   4   4   3
임희진   1   3   2   4   1

In [90]:
#컬럼 이름 바꾸기 
df.rename(columns={'c1':'국어','c2':'수학','c3':'영어','c4':'사회','c5':'과학'},inplace=True)

In [92]:
import numpy as np 
import pandas as pd

a = np.random.randint(1,5,size=(10,5))

list1 = a.tolist()
print(list1,type(list1))

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1)

[[2, 3, 3, 3, 3], [3, 2, 3, 3, 2], [3, 3, 4, 4, 1], [2, 1, 4, 2, 3], [3, 2, 4, 3, 2], [4, 2, 4, 1, 1], [2, 2, 2, 4, 3], [3, 2, 4, 1, 4], [3, 1, 3, 4, 4], [2, 2, 3, 3, 1]] <class 'list'>
   c1  c2  c3  c4  c5
0   2   3   3   3   3
1   3   2   3   3   2
2   3   3   4   4   1
3   2   1   4   2   3
4   3   2   4   3   2
5   4   2   4   1   1
6   2   2   2   4   3
7   3   2   4   1   4
8   3   1   3   4   4
9   2   2   3   3   1


In [95]:
# 열이름을 key로 하고, 리스트를 value로 갖는 딕셔너리 정의 (2창원 배열)

import pandas as pd

dict_data = pd.DataFrame({
    'c0' : np.array([1,2,3,4,5]), 
    'c1' : np.array([31,32,33,34,35]), 
    'c2': np.array([5,6,7,8,9]), 
    'c3': np.array([22,23,24,25,26]), 
    'c4': np.array([13,14,15,16,17]),
    'c5' : np.array([6,7,8,36,37]),
    'c6' : np.array([18,19,20,20,21]),
    'c7' : np.array([12,27,11,12,55])
})
    

print(dict_data)

   c0  c1  c2  c3  c4  c5  c6  c7
0   1  31   5  22  13   6  18  12
1   2  32   6  23  14   7  19  27
2   3  33   7  24  15   8  20  11
3   4  34   8  25  16  36  20  12
4   5  35   9  26  17  37  21  55


In [57]:
dict_data.rename(colums={
    'c0': 'first_single', 
    'c1' : 'second single',
    'c2':'third single',
    'c3':'forth single',
    'c4':'fifth single',
    'c5':'sixth single',
    'c6':'seventh single',
    'c7':'firsth album'}Inplace=True)


SyntaxError: invalid syntax (<ipython-input-57-74ee4e230210>, line 9)

In [98]:
#값 바꾸기 
import warnings
warnings.filterwarnings('ignore')
df_e.rename(columns={'c1':'국어','c2':'영어','c3':'수학','c4':'과학','c5':'음악'},
            index={0:'권준기',1:'우동주',2:'임희진'},inplace=True)
df_e

국어  영어  수학  과학  음악
권준기   2   3   2   2   1
우동주   4   4   4   4   3
임희진   1   3   2   4   1

In [99]:
# df_e.loc['권준기','음악']
df_e.iloc[0,4]

1


##### 과제
##### Q. 생성된 데이터프레임에서 아래 사항을 수행하세요.
- 열이름과 행이름 변경
- 3행만 출력
- 5열만 출력
- 3행 5열의 값 출력
- 4열의 값을 모두 0으로 변경
- 2,3행의 3열 값을 조회(2가지 방법)
- 6행의 2,3,4열의 값을 조회(2가지 방법)
- 2열을 Series와 DataFrame으로 각각 출력
- 2행 3열의 값을 2행 4열의 값과 동일하게 변경
- 2행 3열의 값과 2행 4열의 값을 동시에 만족하는 3,4열을 출력